🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🔮🧗🏽‍♀️🔎🦹

Full error log:
Error:  asset 2022-9-14--22-40-16--8df0c9c1-8012-4e66-8896-434a96346c6c/main.min.js 783 KiB [emitted] (name: main) 1 related asset
runtime modules 937 bytes 4 modules
orphan modules 44 bytes [orphan] 1 module
modules by path ./node_modules/rxjs/dist/esm5/internal/ 204 KiB 221 modules
modules by path ./src/ 50.8 KiB 15 modules
modules by path ./node_modules/destroyable/dist/ 38.5 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB 2 modules
modules by path ./node_modules/waitasecond/dist/ 16.9 KiB 11 modules
modules by path ./node_modules/style-loader/dist/runtime/*.js 5.75 KiB 6 modules
modules by path ./node_modules/css-loader/dist/runtime/*.js 2.94 KiB
./node_modules/css-loader/dist/runtime/sourceMaps.js 688 bytes [built] [code generated]
./node_modules/css-loader/dist/runtime/api.js 2.26 KiB [built] [code generated]
5 modules

ERROR in C:\Users\me\work\collboard\function-builder\src\modules\FunctionBuilderArtModule.tsx
./src/modules/FunctionBuilderArtModule.tsx 34:13-31
[tsl] ERROR in C:\Users\me\work\collboard\function-builder\src\modules\FunctionBuilderArtModule.tsx(34,14)
TS2515: Non-abstract class 'FunctionBuilderArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.
@ ./src/index.ts 3:0-45

ERROR in C:\Users\me\work\collboard\function-builder\src\modules\FunctionBuilderArtModule.tsx
./src/modules/FunctionBuilderArtModule.tsx 34:13-31
[tsl] ERROR in C:\Users\me\work\collboard\function-builder\src\modules\FunctionBuilderArtModule.tsx(34,14)
TS2515: Non-abstract class 'FunctionBuilderArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.
@ ./src/index.ts 3:0-45

ERROR in C:\Users\me\work\collboard\function-builder\src\utils\FunctionBuilderConnectionArt.tsx
./src/utils/FunctionBuilderConnectionArt.tsx 5:13-41
[tsl] ERROR in C:\Users\me\work\collboard\function-builder\src\utils\FunctionBuilderConnectionArt.tsx(5,14)
TS2515: Non-abstract class 'FunctionBuilderConnectionArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.
@ ./src/modules/FunctionBuilderTool.tsx 18:39-87
@ ./src/index.ts 4:0-40

ERROR in C:\Users\me\work\collboard\function-builder\src\utils\FunctionBuilderConnectionArt.tsx
./src/utils/FunctionBuilderConnectionArt.tsx 5:13-41
[tsl] ERROR in C:\Users\me\work\collboard\function-builder\src\utils\FunctionBuilderConnectionArt.tsx(5,14)
TS2515: Non-abstract class 'FunctionBuilderConnectionArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.
@ ./src/modules/FunctionBuilderTool.tsx 18:39-87
@ ./src/index.ts 4:0-40

webpack 5.35.1 compiled with 4 errors in 10132 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\function-builder\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\function-builder\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\function-builder\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\function-builder\node_modules\webpack\lib\Watching.js:201:28)