🚧 Update to SDK 27.23.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🌰👨🏿‍⚕️😸🤾‍♀️

Full error log:
C:\Users\me\work\collboard\function-builder\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
throw ex;
^

Error: listen EADDRINUSE: address already in use :::3000
at Server.setupListenHandle [as _listen2] (node:net:1422:16)
at listenInCluster (node:net:1470:12)
at Server.listen (node:net:1558:7)
at Server.<anonymous> (C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Server\Server.js:151:25)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Server\Server.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Server\Server.js:4:12)
at Server.init (C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Server\Server.js:79:16)
at new Server (C:\Users\me\work\collboard\function-builder\node_modules\@collboard\modules-sdk\dist\colldev\services\Server\Server.js:44:14)
Emitted 'error' event on Server instance at:
at emitErrorNT (node:net:1449:8)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
code: 'EADDRINUSE',
errno: -4091,
syscall: 'listen',
address: '::',
port: 3000
}

Node.js v18.4.0